baseURL = "https://tech1.io/"
title = "Tech1"
theme = "hugo-advance"
paginate = 3
enableGitInfo = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
metaDataFormat = "yaml"
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  google_analytics_id = ""
  enable_dark_mode = false
  enable_nested_menu = false       # allows dropdown menus in main menu
  enable_fixed_header = true      # if true the header will be sticky and animate on scroll
  enable_language_switcher = false

  [params.colors]
    [params.colors.light]
      base = "#ffffff"
      base_offset = "#f2f2f2"
      base_text = "#202020"
      base_text_offset = "#625c5c"
      alt = "#f4f5fb"
      alt_offset = "#CCCCCC"
      alt_text = "#202020"
      alt_text_offset = "#625c5c"
      primary = "#2e2d42"
      primary_offset = "#702bf7"
      primary_text = "#ffffff"
      primary_text_offset = "#79bcff"
    [params.colors.dark]
      base = "#121212"
      base_offset = "#1e1e1e"
      base_text = "#ffffff"
      base_text_offset = "#d7d7d7"
      alt = "#1e1e1e"
      alt_offset = "#2f2f2f"
      alt_text = "#fafafa"
      alt_text_offset = "#a8a4a4"
      primary = "#2b5df7"
      primary_offset = "#a62bf7"
      primary_text = "#eeebfc"
      primary_text_offset = "#a7a7a7"

[params.fonts]
  google_fonts = "https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@700&family=IBM+Plex+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap"
  heading = "IBM Plex Mono"
  base = "IBM Plex Sans"
  monospace = "IBM Plex Mono"

[params.logo]
  logo = "images/logo/logo.svg"                             # Desktop logo
  logo_mobile = "images/logo/logo-mobile.svg"               # Mobile logo, typically the smaller square version of your logo (logomark)
  logo_invert = "images/logo/logo-invert.svg"               # Desktop logo in white, for use when the header is transparent
  logo_invert_mobile = "images/logo/logo-invert-mobile.svg" # Mobile logo in white

[params.seo]
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"
  append_site_title = true                                   # appends the .Site.title to the <title> of all pages

[params.footer]
  show_site_title = false
  show_copyright = false
  show_social_media_links = true
  show_languages = false
  enable_menu_footer_primary = false
  # footer_primary_menu_title = "Product"
  enable_menu_footer_secondary = false
  # footer_secondary_menu_title = "Company"
  enable_menu_footer_tertiary = false
  # footer_tertiary_menu_title = "Support"

[menu]
  [[menu.main]]
    name = "Contact"
    url = "mailto:info@tech1.io"
    weight = 10

[languages]
  [languages.en]
    weight = 0
    languageName = "English"
    contentDir = "content/en"

[permalinks]
  pages = ":slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  portfolio = "portfolio"
  author = "authors"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  