[context.production.environment]
  HUGO_VERSION = "0.102.3"
  HUGO_GOOGLE_ANALYTICS_ID = ""

[context.deploy-preview.environment]
  HUGO_VERSION = "0.102.3"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.102.3"
